#!/usr/bin/env python3
"""tools/build_modelfile.py - GGUFモデルおよび環境情報から最適なModelfileを自動生成し、登録コマンドを提示するスクリプト."""

import argparse
import os
from pathlib import Path
from typing import Dict, Any


def generate_modelfile_content(
    gguf_path: str,
    num_ctx: int = 8192,
    num_thread: int = 8,
    num_gpu: int = 32,
    temperature: float = 0.2,
    top_p: float = 0.9,
    top_k: int = 20,
    repeat_penalty: float = 1.05,
    system_prompt: str = None
) -> str:
    if system_prompt is None:
        system_prompt = (
            "You are an expert software engineer and systems architect.\n"
            "Your task is to help the user with precise, highly efficient, and bug-free code.\n"
            "When asked to perform file operations, structural log analysis, or tool executions, "
            "ensure that your responses conform strictly to the required schema or functional calling format without any conversational filler.\n"
            "Always prioritize code portability, utilizing standard libraries or designated robust frameworks."
        )

    content = f"""# ==============================================================================
# Ollama Modelfile (Generated by second-brain-graph build_modelfile.py)
# ==============================================================================

FROM {gguf_path}

# Hardware / Resource Parameters
PARAMETER num_ctx {num_ctx}
PARAMETER num_thread {num_thread}
PARAMETER num_gpu {num_gpu}

# Inference Tuning Parameters
PARAMETER temperature {temperature}
PARAMETER top_p {top_p}
PARAMETER top_k {top_k}
PARAMETER repeat_penalty {repeat_penalty}

# Chat Template (Qwen / Standard Format)
TEMPLATE \"\"\"{{{{ if .System }}}}<|im_start|>system
{{{{ .System }}}}<|im_end|>
{{{{ end }}}}{{{{ if .Prompt }}}}<|im_start|>user
{{{{ .Prompt }}}}<|im_end|>
{{{{ end }}}}<|im_start|>assistant
{{{{ .Response }}}}<|im_end|>\"\"\"

# System Prompt
SYSTEM \"\"\"{system_prompt}\"\"\"
"""
    return content


def get_modelfiles_dir() -> Path:
    project_root = Path(__file__).resolve().parent.parent
    modelfiles_dir = project_root / "tools" / "modelfiles"
    modelfiles_dir.mkdir(parents=True, exist_ok=True)
    return modelfiles_dir


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate Ollama Modelfile with report and command prompt.")
    parser.add_argument("--gguf-path", required=True, help="Path to the GGUF model file")
    parser.add_argument("--model-name", required=True, help="Base model identifier name (e.g. qwen3.6-35b-iq4)")
    parser.add_argument("--role", default="coder", help="Role tag (e.g., coder, planner, reviewer)")
    parser.add_argument("--num-ctx", type=int, default=8192, help="Context window size")
    parser.add_argument("--num-thread", type=int, default=8, help="CPU threads")
    parser.add_argument("--num-gpu", type=int, default=32, help="GPU layers offload")
    parser.add_argument("--temperature", type=float, default=0.2, help="Temperature")
    parser.add_argument("--repeat-penalty", type=float, default=1.05, help="Repeat penalty")

    args = parser.parse_args()

    # Naming convention: Modelfile_<model_name>_<role>
    filename = f"Modelfile_{args.model_name}_{args.role}"
    output_path = get_modelfiles_dir() / filename

    content = generate_modelfile_content(
        gguf_path=args.gguf_path,
        num_ctx=args.num_ctx,
        num_thread=args.num_thread,
        num_gpu=args.num_gpu,
        temperature=args.temperature,
        repeat_penalty=args.repeat_penalty
    )

    with open(output_path, "w", encoding="utf-8") as f:
        f.write(content)

    print(f"\n==================================================================")
    print(f"📋 Modelfile 生成完了報告")
    print(f"==================================================================")
    print(f"1. 生成ファイル情報:")
    print(f"   - Modelfile 保存先: {output_path}")
    print(f"   - ベース GGUF パス: {args.gguf_path}\n")

    print(f"2. 設定パラメーターと根拠:")
    print(f"   - num_ctx:        {args.num_ctx} (コンテキスト window とメモリバランス考慮)")
    print(f"   - num_thread:     {args.num_thread} (CPU 物理コア数に最適化)")
    print(f"   - num_gpu:        {args.num_gpu} (VRAM オフロードレイヤー数)")
    print(f"   - temperature:    {args.temperature} (決定論的生成に向け低下)")
    print(f"   - repeat_penalty: {args.repeat_penalty} (無限ループ防止)\n")

    registered_name = f"{args.model_name}:{args.role}"
    rel_modelfile_path = Path("tools") / "modelfiles" / filename
    print(f"3. 手動登録用コマンド (確認の上、実行してください):")
    print(f"```bash")
    print(f"ollama create {registered_name} -f ./{rel_modelfile_path}")
    print(f"```")
    print(f"==================================================================\n")


if __name__ == "__main__":
    main()
